import type { Locale } from "@/config/site";

/**
 * PLAIN-LANGUAGE DRAFTS (DESIGN-GUIDELINES §1.15: "lawyer review required"). Written from what the product actually does:
 * Facebook Login connects a Page, Graph webhooks deliver messages, conversations / catalog / bookings / FAQs are stored,
 * disconnecting a Page deletes its stored token, and replies are generated by a third-party AI model.
 * Tokens: {company} and {contact} are filled from src/config/owner.ts (the contact falls back to the Messenger page).
 */
export type LegalSection = { id?: string; h: string; p?: string[]; list?: string[] };
export type LegalDoc = { title: string; intro: string; sections: LegalSection[] };
export type LegalSet = {
  draftNote: string;
  updatedLabel: string;
  updated: string;
  privacy: LegalDoc;
  terms: LegalDoc;
  deletion: LegalDoc;
};

const en: LegalSet = {
  draftNote: "Draft: this text has not yet been reviewed by a lawyer.",
  updatedLabel: "Last updated",
  updated: "30 September 2026",

  privacy: {
    title: "Privacy policy",
    intro:
      "Chaster is an assistant and inbox for businesses that sell through Facebook Messenger and Instagram. This page explains what data Chaster processes, why, who receives it, and how to have it deleted.",
    sections: [
      {
        h: "Who is responsible",
        p: ["Chaster is operated by {company}. You can reach us at {contact}."],
      },
      {
        h: "What we process",
        list: [
          "Connection data: the name and ID of the Facebook Page you connect, the Instagram account linked to it, and an access token that lets Chaster read and send messages for that Page.",
          "Conversation data: messages between your customers and your Page (text, photos, reactions and times), the identifiers and names Meta provides for those customers, and short summaries the assistant keeps so it can follow a conversation.",
          "Business content you add: questions and answers, catalog items with prices and photos, opening hours and address, staff and rooms, and bookings (time, service and the contact details a customer gives).",
          "Account settings and a log of the assistant's replies, so you can review them.",
          "Website measurement: if analytics is switched on and you agree to it, which buttons on this website are clicked.",
        ],
      },
      {
        h: "Why we process it",
        p: [
          "To provide the service: show conversations in one inbox, let the assistant answer from your own content, make and manage bookings, and let you take over any chat. To keep the service secure. To improve this website, only with your consent.",
        ],
      },
      {
        h: "Who receives it",
        list: [
          "Meta, because messages and Page access come through Facebook and Instagram.",
          "Cloud hosting and database providers that store the data for us.",
          "An AI language-model provider that receives the text of a conversation and your business content in order to write a reply.",
        ],
        p: ["We do not sell personal data."],
      },
      {
        h: "How long we keep it",
        p: ["For as long as the Page stays connected, and until you ask us to delete it. See the section below."],
      },
      {
        id: "data-deletion",
        h: "Deleting your data",
        p: [
          "You can disconnect a Page in Chaster at any time, which deletes its stored access token. To have conversations, catalog, bookings and questions deleted as well, follow the steps on our data deletion page, or contact us at {contact}.",
        ],
      },
      {
        h: "Your rights",
        p: ["You can ask us for a copy of your data, to correct it, or to delete it. Write to {contact} and we will answer without undue delay."],
      },
      {
        h: "Changes",
        p: ["If this policy changes, the new version will be published here with a new date."],
      },
    ],
  },

  terms: {
    title: "Terms of use",
    intro: "These terms apply when you use Chaster. By connecting a Page you agree to them.",
    sections: [
      {
        h: "The service",
        p: ["Chaster shows your Messenger and Instagram conversations in one inbox and can reply to customers on your Page's behalf, using the questions, catalog, hours and bookings you provide."],
      },
      {
        h: "Your Page and your content",
        p: [
          "You confirm that you have the right to connect the Page and to use its conversations and the content you add. You remain responsible for what is published under your Page's name and for following Meta's terms.",
        ],
      },
      {
        h: "The AI assistant",
        p: [
          "Replies are generated automatically from your content and may sometimes be wrong. You can take over any conversation at any time, and the assistant stays silent until you hand it back. You are responsible for business decisions made in your conversations.",
        ],
      },
      {
        h: "Free period and payment",
        p: ["The free period, prices and billing terms are shown in the app before you pay. Prices are in Georgian lari."],
      },
      {
        h: "Availability",
        p: ["We work to keep Chaster available but cannot promise uninterrupted service, since it depends on Meta's platforms."],
      },
      {
        h: "Ending the agreement",
        p: ["You can disconnect your Page and stop using Chaster at any time. We may suspend the service if these terms are broken."],
      },
      {
        h: "Liability and law",
        p: ["To the extent the law allows, Chaster is provided as it is and our liability is limited to the fees you paid in the last three months. Georgian law applies."],
      },
      { h: "Contact", p: ["{company}, {contact}."] },
    ],
  },

  deletion: {
    title: "Data deletion",
    intro: "You decide what happens to your data. Here is how to have it deleted.",
    sections: [
      {
        h: "If you use Chaster for your business",
        list: [
          "Open Chaster, open the Page menu and choose to disconnect the Page. This deletes the stored access token.",
          "Write to {contact} from the address linked to your account, with the subject “Delete my data” and the name of your Page.",
          "We delete the conversations, catalog, bookings and questions of that Page without undue delay and confirm to you.",
        ],
      },
      {
        h: "If you are a customer of a business that uses Chaster",
        p: [
          "Write to {contact} with the name you use on Facebook or Instagram and the name of the business. We will help delete your messages from Chaster. Your conversation also exists inside Facebook and Instagram, which you can manage in Meta's own settings.",
        ],
      },
      {
        h: "Remove Chaster from Facebook",
        p: ["In your Facebook settings, open Business Integrations and remove Chaster. This withdraws its access to your Page immediately."],
      },
      {
        h: "What we may keep",
        p: ["Only what the law requires us to keep, such as invoices."],
      },
    ],
  },
};

const ka: LegalSet = {
  draftNote: "პროექტი: ეს ტექსტი ჯერ არ შემოუმოწმებია იურისტს.",
  updatedLabel: "ბოლო განახლება",
  updated: "2026 წლის 30 სექტემბერი",

  privacy: {
    title: "კონფიდენციალურობის პოლიტიკა",
    intro:
      "Chaster არის ასისტენტი და ინბოქსი ბიზნესებისთვის, რომლებიც Facebook Messenger-სა და Instagram-ში ყიდიან. ამ გვერდზე წერია, რა მონაცემებს ამუშავებს Chaster, რატომ, ვის გადაეცემა და როგორ წაიშლება.",
    sections: [
      {
        h: "ვინ არის პასუხისმგებელი",
        p: ["Chaster-ს მართავს {company}. დაგვიკავშირდი: {contact}."],
      },
      {
        h: "რას ვამუშავებთ",
        list: [
          "კავშირის მონაცემები: შენ მიერ დაკავშირებული Facebook გვერდის სახელი და ID, მასთან დაკავშირებული Instagram ანგარიში და წვდომის ტოკენი, რომლითაც Chaster გვერდის სახელით კითხულობს და აგზავნის შეტყობინებებს.",
          "საუბრის მონაცემები: შეტყობინებები შენს კლიენტებსა და შენს გვერდს შორის (ტექსტი, ფოტოები, რეაქციები და დრო), კლიენტების იდენტიფიკატორები და სახელები, რასაც Meta გვაძლევს, და მოკლე შეჯამებები, რომლებსაც ასისტენტი ინახავს, რომ საუბარს მიჰყვეს.",
          "ბიზნესის შენ მიერ დამატებული ინფორმაცია: კითხვა-პასუხები, კატალოგი ფასებითა და ფოტოებით, სამუშაო საათები და მისამართი, თანამშრომლები და ოთახები, ჯავშნები (დრო, სერვისი და კლიენტის მიერ მითითებული საკონტაქტო მონაცემები).",
          "ანგარიშის პარამეტრები და ასისტენტის პასუხების ჩანაწერი, რომ გადახედო.",
          "საიტის გაზომვა: თუ ანალიტიკა ჩართულია და თანახმა ხარ, რომელ ღილაკებს აჭერენ ამ საიტზე.",
        ],
      },
      {
        h: "რატომ ვამუშავებთ",
        p: [
          "სერვისის უზრუნველსაყოფად: საუბრები ერთ ინბოქსში, ასისტენტის პასუხები შენი ინფორმაციით, ჯავშნების გაკეთება და მართვა და შესაძლებლობა, ნებისმიერ ჩატში ჩაერთო. სერვისის უსაფრთხოებისთვის. ამ საიტის გასაუმჯობესებლად — მხოლოდ შენი თანხმობით.",
        ],
      },
      {
        h: "ვის გადაეცემა",
        list: [
          "Meta-ს, რადგან შეტყობინებები და გვერდზე წვდომა Facebook-სა და Instagram-ზე გადის.",
          "ღრუბლოვანი ჰოსტინგისა და მონაცემთა ბაზის პროვაიდერებს, რომლებიც მონაცემებს ჩვენთვის ინახავენ.",
          "AI ენობრივი მოდელის პროვაიდერს, რომელიც პასუხის დასაწერად იღებს საუბრის ტექსტს და შენი ბიზნესის ინფორმაციას.",
        ],
        p: ["პერსონალურ მონაცემებს არ ვყიდით."],
      },
      {
        h: "რამდენ ხანს ვინახავთ",
        p: ["სანამ გვერდი დაკავშირებულია და სანამ არ მოგვთხოვ წაშლას. იხილე ქვემოთ."],
      },
      {
        id: "data-deletion",
        h: "მონაცემების წაშლა",
        p: [
          "გვერდის გათიშვა Chaster-ში ნებისმიერ დროს შეგიძლია, რაც წაშლის შენახულ წვდომის ტოკენს. საუბრების, კატალოგის, ჯავშნებისა და კითხვების წასაშლელად მიჰყევი ნაბიჯებს მონაცემების წაშლის გვერდზე ან მოგვწერე: {contact}.",
        ],
      },
      {
        h: "შენი უფლებები",
        p: ["შეგიძლია მოგვთხოვო შენი მონაცემების ასლი, შესწორება ან წაშლა. მოგვწერე: {contact} და დაუყოვნებლივ გიპასუხებთ."],
      },
      {
        h: "ცვლილებები",
        p: ["პოლიტიკის შეცვლის შემთხვევაში ახალი ვერსია ახალი თარიღით აქვე გამოქვეყნდება."],
      },
    ],
  },

  terms: {
    title: "გამოყენების პირობები",
    intro: "ეს პირობები მოქმედებს, როცა Chaster-ს იყენებ. გვერდის დაკავშირებით მათ ეთანხმები.",
    sections: [
      {
        h: "სერვისი",
        p: ["Chaster გაჩვენებს შენს Messenger და Instagram საუბრებს ერთ ინბოქსში და შეუძლია კლიენტებს შენი გვერდის სახელით უპასუხოს იმ კითხვების, კატალოგის, საათებისა და ჯავშნების მიხედვით, რასაც თავად შეიყვან."],
      },
      {
        h: "შენი გვერდი და შენი ინფორმაცია",
        p: [
          "ადასტურებ, რომ გაქვს გვერდის დაკავშირებისა და მისი საუბრებისა და შენ მიერ დამატებული ინფორმაციის გამოყენების უფლება. შენ რჩები პასუხისმგებელი იმაზე, რაც შენი გვერდის სახელით ქვეყნდება, და Meta-ს პირობების დაცვაზე.",
        ],
      },
      {
        h: "AI ასისტენტი",
        p: [
          "პასუხები ავტომატურად იქმნება შენი ინფორმაციიდან და ზოგჯერ შეიძლება არასწორი იყოს. ნებისმიერ საუბარში ნებისმიერ დროს შეგიძლია ჩაერთო და ასისტენტი ჩუმადაა, სანამ არ დააბრუნებ. შენს საუბრებში მიღებულ ბიზნეს გადაწყვეტილებებზე პასუხისმგებელი ხარ შენ.",
        ],
      },
      {
        h: "უფასო პერიოდი და გადახდა",
        p: ["უფასო პერიოდს, ფასებსა და გადახდის პირობებს გადახდამდე აპლიკაციაში დაინახავ. ფასები ლარშია."],
      },
      {
        h: "ხელმისაწვდომობა",
        p: ["ვცდილობთ, Chaster ყოველთვის ხელმისაწვდომი იყოს, მაგრამ უწყვეტ მუშაობას ვერ დავპირდებით, რადგან ის Meta-ს პლატფორმებზეა დამოკიდებული."],
      },
      {
        h: "ხელშეკრულების შეწყვეტა",
        p: ["გვერდის გათიშვა და Chaster-ის გამოყენების შეწყვეტა ნებისმიერ დროს შეგიძლია. პირობების დარღვევის შემთხვევაში სერვისი შეიძლება შევაჩეროთ."],
      },
      {
        h: "პასუხისმგებლობა და კანონი",
        p: ["კანონით დაშვებულ ფარგლებში Chaster მოწოდებულია „როგორც არის“ და ჩვენი პასუხისმგებლობა შემოიფარგლება ბოლო სამი თვის განმავლობაში გადახდილი თანხით. მოქმედებს საქართველოს კანონმდებლობა."],
      },
      { h: "კონტაქტი", p: ["{company}, {contact}."] },
    ],
  },

  deletion: {
    title: "მონაცემების წაშლა",
    intro: "შენ წყვეტ, რა მოუვა შენს მონაცემებს. აი, როგორ წაშალო ისინი.",
    sections: [
      {
        h: "თუ Chaster-ს შენი ბიზნესისთვის იყენებ",
        list: [
          "გახსენი Chaster, გახსენი გვერდის მენიუ და აირჩიე გვერდის გათიშვა. ეს წაშლის შენახულ წვდომის ტოკენს.",
          "მოგვწერე: {contact} იმ მისამართიდან, რომელიც ანგარიშთანაა დაკავშირებული, თემად მიუთითე „ჩემი მონაცემების წაშლა“ და გვერდის სახელი.",
          "იმ გვერდის საუბრებს, კატალოგს, ჯავშნებსა და კითხვებს დაუყოვნებლივ წავშლით და დაგიდასტურებთ.",
        ],
      },
      {
        h: "თუ იმ ბიზნესის კლიენტი ხარ, რომელიც Chaster-ს იყენებს",
        p: [
          "მოგვწერე: {contact}, მიუთითე სახელი, რომლითაც Facebook-ზე ან Instagram-ზე ხარ, და ბიზნესის სახელი. დაგეხმარებით შეტყობინებების წაშლაში Chaster-იდან. შენი საუბარი Facebook-სა და Instagram-შიც არსებობს და მას Meta-ს პარამეტრებში მართავ.",
        ],
      },
      {
        h: "Chaster-ის მოცილება Facebook-იდან",
        p: ["Facebook-ის პარამეტრებში გახსენი Business Integrations და ამოშალე Chaster. ეს მყისიერად გააუქმებს მის წვდომას შენს გვერდზე."],
      },
      {
        h: "რას შეიძლება ვინახავდეთ",
        p: ["მხოლოდ იმას, რისი შენახვაც კანონით გვევალება, მაგალითად, ინვოისებს."],
      },
    ],
  },
};

export const LEGAL: Record<Locale, LegalSet> = { ka, en };
