"""Subset FiraGO into the three web weights used by the site (DESIGN-GUIDELINES §2.2).

Run:  python design/tools/build_fonts.py
Needs: pip install fonttools brotli
Output: src/fonts/chaster-sans-{400,500,600}.woff2 and src/fonts/OFL.txt

What it does
- Fetches FiraGO Regular / Medium / SemiBold (OFL 1.1) from bBoxType/FiraGO if not cached.
- Keeps: Basic Latin, Latin-1, Georgian U+10A0-10FF, general punctuation U+2010-2027,
  U+2009 (thin space), U+202F, U+00A0 and the Lari sign U+20BE.
- Drops hinting (modern rasterisers ignore it) and everything outside those ranges.
- Renames the family to "Chaster Sans". Subsetting is a modification under the OFL, and the
  upstream README adds the Reserved Font Name "Fira", so the subset must not carry the original name.
  Copyright and licence name records (IDs 0, 13, 14) are kept as the OFL requires.

The metric-matched fallback font is generated by next/font/local at build time (adjustFontFallback),
so this script does not need to compute it.
"""
import os
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
CACHE = os.path.join(os.environ.get("TEMP", "."), "chaster_fonts")
OUT = os.path.join(ROOT, "src", "fonts")
BASE = "https://github.com/bBoxType/FiraGO/raw/master/Fonts/FiraGO_TTF_1001/Roman"
WEIGHTS = {400: "Regular", 500: "Medium", 600: "SemiBold"}

UNICODES = (
    list(range(0x0020, 0x007F))
    + list(range(0x00A0, 0x0100))
    + list(range(0x10A0, 0x1100))
    + list(range(0x2010, 0x2028))
    + [0x2009, 0x202F, 0x20BE]
)
FEATURES = ["kern", "tnum", "lnum", "locl", "ccmp", "liga", "calt", "case"]


def fetch(weight_name: str) -> str:
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, f"FiraGO-{weight_name}.ttf")
    if not os.path.exists(path):
        print("downloading", weight_name)
        urllib.request.urlretrieve(f"{BASE}/FiraGO-{weight_name}.ttf", path)
    return path


def rename(font: TTFont, style: str):
    family = "Chaster Sans"
    full = f"{family} {style}"
    ps = f"ChasterSans-{style}"
    name = font["name"]
    for rec in list(name.names):
        if rec.nameID in (1, 3, 4, 6, 16, 17, 18, 21, 22, 25):
            name.removeNames(nameID=rec.nameID)
    for plat, enc, lang in ((3, 1, 0x409), (1, 0, 0)):
        name.setName(family, 1, plat, enc, lang)
        name.setName(style if style in ("Regular", "Bold", "Italic") else "Regular", 2, plat, enc, lang)
        name.setName(f"{ps};subset", 3, plat, enc, lang)
        name.setName(full, 4, plat, enc, lang)
        name.setName(ps, 6, plat, enc, lang)
        if style != "Regular":
            name.setName(family, 16, plat, enc, lang)
            name.setName(style, 17, plat, enc, lang)


def build(weight: int, weight_name: str):
    font = TTFont(fetch(weight_name))
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.hinting = False
    opts.layout_features = FEATURES
    opts.name_IDs = [0, 1, 2, 3, 4, 6, 13, 14, 16, 17]
    opts.notdef_outline = True
    opts.glyph_names = False
    opts.legacy_kern = False
    opts.drop_tables += ["DSIG", "FFTM", "MATH"]
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=UNICODES)
    sub.subset(font)
    rename(font, weight_name)
    os.makedirs(OUT, exist_ok=True)
    out = os.path.join(OUT, f"chaster-sans-{weight}.woff2")
    font.flavor = "woff2"
    font.save(out)
    kb = os.path.getsize(out) / 1024
    cmap = font.getBestCmap()
    check = {
        "lari": 0x20BE in cmap,
        "georgian": all(c in cmap for c in range(0x10D0, 0x10FB)),
        "low9quote": 0x201E in cmap and 0x201C in cmap,
        "nbsp": 0xA0 in cmap,
    }
    print(f"{weight} {weight_name:9s} {kb:5.1f} KB  glyphs={len(cmap)}  {check}")
    if kb > 45:
        print("   WARNING: over the 45 KB target")


def main():
    for w, n in WEIGHTS.items():
        build(w, n)
    lic = os.path.join(CACHE, "OFL.txt")
    if not os.path.exists(lic):
        urllib.request.urlretrieve("https://raw.githubusercontent.com/bBoxType/FiraGO/master/OFL.txt", lic)
    with open(lic, "rb") as f:
        body = f.read()
    note = (
        b"Chaster Sans is a subset of FiraGO (Georgian, Latin, punctuation, Lari sign), hinting removed and renamed.\r\n"
        b"Source: https://github.com/bBoxType/FiraGO  -  licensed under the SIL Open Font License 1.1 below.\r\n\r\n"
    )
    with open(os.path.join(OUT, "OFL.txt"), "wb") as f:
        f.write(note + body)


if __name__ == "__main__":
    main()
