// Extracts wordmark paths and the reference mark paths from the kit SVGs in src/brand/kit
// into src/brand/lockups.generated.ts. The wordmark is supplied as outlines by the brand kit
// and must never be retyped or redrawn (see kit README), so we carry the paths verbatim.
//
// Run: node scripts/extract-brand.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const kit = path.join(root, "src", "brand", "kit");
const read = (n) => fs.readFileSync(path.join(kit, n), "utf8");

const MARGIN = 28; // the kit adds one cell of clear space on every side; we crop it (the layout supplies its own)

function parseLockup(file) {
  const s = read(file);
  const vb = s.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  const width = +(parseFloat(vb[1]) - 2 * MARGIN).toFixed(3);
  const height = +(parseFloat(vb[2]) - 2 * MARGIN).toFixed(3);
  const groups = [...s.matchAll(/<g transform="translate\(([\d.]+) ([\d.]+)\) scale\(1\)">(.*?)<\/g>/g)];
  if (groups.length !== 2) throw new Error(`${file}: expected 2 inner groups, got ${groups.length}`);
  const [markG, wordG] = groups;
  const paths = (g) => [...g[3].matchAll(/<path d="([^"]+)" fill="(#[0-9A-Fa-f]{6})"/g)].map((m) => ({ d: m[1], fill: m[2] }));
  const mark = paths(markG);
  const word = paths(wordG);
  return {
    width,
    height,
    markWhiteD: mark[0].d,
    markSignalD: mark[1].d,
    wordmark: { x: parseFloat(wordG[1]), y: parseFloat(wordG[2]), d: word[0].d },
    // custom-r only: the detached rounded "booked cell" that replaces the arm of the final r
    wordmarkCell: word[1] ? word[1].d : null,
  };
}

const standard = parseLockup("chaster-lockup-horizontal-standard-dark.svg");
const customR = parseLockup("chaster-lockup-horizontal-custom-r-dark.svg");

// reference paths for verify-brand.ts
const symDark = read("chaster-symbol-dark.svg");
const symMono = read("chaster-symbol-mono.svg");
const refs = {
  darkWhite: symDark.match(/<path d="([^"]+)" fill="#FFFFFF"\/>/)[1],
  darkSignal: symDark.match(/<path d="([^"]+)" fill="#AB97FF" fill-rule="evenodd"\/>/)[1],
  monoAll: symMono.match(/<path d="([^"]+)" fill="#0D0A1B" fill-rule="evenodd"\/>/)[1],
};

const out = `// GENERATED by scripts/extract-brand.mjs from src/brand/kit. Do not edit by hand.
export const LOCKUP_STANDARD = ${JSON.stringify(standard, null, 2)} as const;

export const LOCKUP_CUSTOM_R = ${JSON.stringify(customR, null, 2)} as const;

export const KIT_REFERENCE = ${JSON.stringify(refs, null, 2)} as const;
`;
fs.writeFileSync(path.join(root, "src", "brand", "lockups.generated.ts"), out);

// Messenger and Instagram glyphs (24 x 24, monochrome). Source: Simple Icons (CC0 data; the marks themselves
// belong to Meta, so they are used only as functional labels with Meta's clear space respected).
const chDir = path.join(root, "src", "brand", "channels");
const glyph = (n) => fs.readFileSync(path.join(chDir, `${n}.svg`), "utf8").match(/<path d="([^"]+)"/)[1];
fs.writeFileSync(
  path.join(root, "src", "brand", "channels.generated.ts"),
  `// GENERATED by scripts/extract-brand.mjs from src/brand/channels. Do not edit by hand.
export const CHANNEL_GLYPHS = {
  messenger: ${JSON.stringify(glyph("messenger"))},
  instagram: ${JSON.stringify(glyph("instagram"))},
} as const;
`,
);
console.log(
  "standard:",
  `${standard.width} x ${standard.height}`,
  "| custom-r:",
  `${customR.width} x ${customR.height}`,
  "| wordmark d length",
  standard.wordmark.d.length,
  customR.wordmark.d.length,
);
